name: Run Daily Tech Pulse Monitor

on:
  # Runs once a day at 1 AM UTC. 
  schedule:
    - cron: '0 1 * * *'
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-pulse-monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 

      - name: Install dependencies
        run: pip install -r requirements.txt
              
      - name: Run the pulse monitor script     
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PRODUCT_HUNT_TOKEN: ${{ secrets.PRODUCT_HUNT_TOKEN }}
        run: python main.py
